<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function createCandidate($name)
	{
		$newUser = new User();
		$newUser->setName($name);
		$newUser->setIsInterviewer(false);

		$this->getEntityManager()->persist($newUser);
		$this->getEntityManager()->flush();

		//throw qualquer coisa se isto correr mal!
	}

	public function createInterviewer($name)
	{
		$newUser = new User();
		$newUser->setName($name);
		$newUser->setIsInterviewer(true);

		$this->getEntityManager()->persist($newUser);
		$this->getEntityManager()->flush();

		//throw qualquer coisa se isto correr mal!
	}

	public function getInterviewer($id)
	{
		$user = $this->find($id);

		if ($user && $user->isInterviewer()) {
			return $user;
		}

	//isto era bem feito era a enviar excepções
		return null;
	}

	public function getAllInterviewers()
	{
		$criteria = array('isInterviewer' => true);
		$interviewers = $this->findBy($criteria);

		return $interviewers;
	}

	public function getCandidate($id)
	{
		$user = $this->find($id);
		
		if ($user && !$user->isInterviewer()) {
			return $user;
		}

		//isto era bem feito era a enviar excepções
		return null;
	}

	public function getAllCandidates()
	{
		$criteria = array('isInterviewer' => false);
		$candidates = $this->findBy($criteria);

		return $candidates;
	}
}
